### ISSUE TITLE
Deployment acceptance

### ISSUE THREAD

**Issue by gilleswittenberg** [Amsterdam/zaken-frontend#118]
- [x] Auto deploy master to acceptance
- [x] Check acceptance domain (acc.zaken.amsterdam.nl)
- [x] Logging using sentry
- [x] Switch tussen acceptance en production build, hosting

**Comment by peterboer** [comment]
@Jeffrey-Zutt kan jij deze testen en dan evt. afvinken én doorzetten naar done?
