### ISSUE TITLE
🎨  UX - Eerste opzet weergave Invorderingen

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/zaken-frontend#192]
- [x] doornemen info met mexime
- [x] plannen gesprekken informatiebehoefte handhavers
- [x] doornemen synoniemen of niet met geert
- [x] opzet maken + doornemen met team
- [x] test gebruikers
- [x] globaal omschrijven functionaliteit

**Comment by NvElten-UX** [comment]
Mex neemt contact op met technisch beheerder van API om te kijken naar de verschillende terminologie
