### ISSUE TITLE
Tonen Invorderingen (Frontend)

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/zaken-frontend#208]
- [x] Tonen resultaat API
- [ ] Implementeren 'extra informatie' knopje én modal

- [ ] vraagteken comform styleguide

- [ ] groenvinkje als status (gefactureerd) vanuit belastingen wordt gepushed. als status bwv is, dan een in progress icoon.

- [x] Titel in meervouw 'Invorderingsbesluiten' als meer dan 1 invordering. bij 1 invordering wel enkelvoud 'Invorderingsbesluit'

- [x] datum schrijven als: 26 september 2019

**Comment by petercuret** [comment]
@gilleswittenberg @Jeffrey-Zutt De invorderingen komen nu mee. 
De volgende zaken hebben data.
https://acc.zaken.top.amsterdam.nl/cases/169896_1
https://acc.zaken.top.amsterdam.nl/cases/1854595_1

(Zie states_with_fines in het response object. Het 'items' object op het hoogste niveau is deprecated en mag er straks uit.)
