### ISSUE TITLE
BAG (FE): tabel op adres detail tab

### ISSUE THREAD

**Issue by NvElten-UX** [Amsterdam/zaken-frontend#233]
- [ ] Adres tonen als:
Sint Luciensteeg 19
1012 PM  Amsterdam

- [ ] wel tonen Bestemming 'subtype': _verblijfsobject_

- [ ] BAG uitzoeken waar de gegevens staan betreft #kamers, #bouwlagen en oppervlakte (nu in eerste dump niet getoond)

**Comment by peterboer** [comment]
verplaatst naar Jira
