### ISSUE TITLE
Datum formatting

### ISSUE THREAD

**Issue by gilleswittenberg** [Amsterdam/zaken-frontend#249]
Sitewide displaying of dates in Gemeente Amsterdam standard format

- [x] Decide on which format to use
- [x] Implement util function / React Component
- [x] Implement "26-08-2020" format

**Comment by NvElten-UX** [comment]
Overal op de website van Amsterdam en mijn Amsterdam zie ik dat de datum als volgt wordt geschreven:
24 maart 2020

dus dag en jaar in cijfers, maand voluit geschreven.
