### ISSUE TITLE
notitie 'toegang verleend' tonen in looplijst overzicht zoals oorspronkelijk ontwikkeld

### ISSUE THREAD

**Issue by NvElten-UX** [Amsterdam/zaken-frontend#254]
- [ ] Gemaakte notities blijven, net zoals nu op p, zichtbaar in de looplijst. Om de notitie in zijn geheel te kunnen zien kan gebruiker op notitie icon klikken.
https://www.sketch.com/s/084927de-b180-4bf7-901c-efd56c6a5a93/a/8K1e4x

- [ ] Indien gebruiker weer op notitie item klikt, ziet hij zijn eigen concept notities en kan deze wijzigen. Daarbij zijn ook andere notities zichtbaar van collega indien deze een gemaakt heeft.
https://www.sketch.com/s/084927de-b180-4bf7-901c-efd56c6a5a93/a/2oAdj5

**Comment by peterboer** [comment]
Verplaatst naar Jira
